language: swift
osx_image: xcode9.3
install:
  gem update --system --no-document
  bundle install
  pod repo update --silent
script:
  set -o pipefail &&
  xcodebuild -workspace OmiseGO.xcworkspace -scheme "OmiseGO" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" test | xcpretty &&
  pod lib lint;
