language: swift
osx_image: xcode9.3
before_install:
- pod update
script:
  set -o pipefail &&
  xcodebuild -workspace OmiseGO.xcworkspace -scheme "OmiseGO" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" test | xcpretty &&
  pod lib lint;
